spring:
  application:
    name: spring-security-oauth2
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      url: jdbc:mysql://127.0.0.1:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: l19980207
server:
  port: 8080
mybatis:
  type-aliases-package: com.oauth.domain
  mapper-locations: classpath:mapper/*.xml